services:
  postgres:
    image: pgvector/pgvector:pg16
    environment:
      POSTGRES_USER: ${DATABASE_USER:-user}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD:-password}
      POSTGRES_DB: ${DATABASE_NAME:-dbname}
      POSTGRES_INITDB_ARGS: "--no-locale --encoding=UTF8"
    command: >
      bash -c "
        docker-entrypoint.sh postgres &
        sleep 10 &&
        psql -U ${DATABASE_USER:-user} -d ${DATABASE_NAME:-dbname} -c 'CREATE EXTENSION IF NOT EXISTS vector;' &&
        wait
      "
    volumes:
      - slack_postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  redis:
    image: redis:7
    ports:
      - "6379:6379"

  server:
    image: ${IMAGE_TAG}
    ports:
      - "80:80"
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - REDIS_URL=${REDIS_URL}
      - PORT=${PORT:-80}
      - JWT_SECRET=${JWT_SECRET}
      - JWT_ACCESS_EXPIRATION=${JWT_ACCESS_EXPIRATION:-15m}
      - JWT_REFRESH_EXPIRATION=${JWT_REFRESH_EXPIRATION:-7d}
      - SLACK_AWS_REGION=${SLACK_AWS_REGION}
      - SLACK_AWS_ACCESS_KEY_ID=${SLACK_AWS_ACCESS_KEY_ID}
      - SLACK_AWS_SECRET_ACCESS_KEY=${SLACK_AWS_SECRET_ACCESS_KEY}
      - SLACK_AWS_S3_BUCKET=${SLACK_AWS_S3_BUCKET}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - DEFAULT_WORKSPACE_ID=${DEFAULT_WORKSPACE_ID}
      - DEFAULT_CHANNEL_ID=${DEFAULT_CHANNEL_ID}
    depends_on:
      - postgres
      - redis

volumes:
  slack_postgres_data:
